# Generated by Django 5.2.8 on 2025-12-07 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_eventokafka_delete_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventokafka',
            options={'ordering': ['-creado_at']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado_at']},
        ),
        migrations.RemoveField(
            model_name='eventokafka',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='eventokafka',
            name='recibido_at',
        ),
        migrations.RemoveField(
            model_name='eventokafka',
            name='topic',
        ),
        migrations.AddField(
            model_name='eventokafka',
            name='accion',
            field=models.CharField(db_index=True, default='desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventokafka',
            name='creado_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventokafka',
            name='datos',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventokafka',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='app_core.producto'),
        ),
        migrations.AddField(
            model_name='eventokafka',
            name='usuario',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='eventokafka',
            index=models.Index(fields=['creado_at'], name='idx_eventokafka_creado_at'),
        ),
        migrations.AddIndex(
            model_name='eventokafka',
            index=models.Index(fields=['accion'], name='idx_eventokafka_accion'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='idx_producto_precio'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-creado_at'], name='idx_producto_creado_at'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_producto_nombre'),
        ),
    ]
